server:
  port: 8081

spring:
  application:
    name: payments
  datasource:
    url: jdbc:mysql://localhost:3306/ECommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect